### ISSUE TITLE
"message":"API rate limit exceeded 

### ISSUE THREAD

**Issue by LuigiBella** [gis-ops/wordpress-markdown-git#14]
**Versions**
Wordpress: 5.4.1
Documents for Git: Markdown Git Version 0.1 (version released on March 8th)

**Describe the bug**
Even though the shortcode used is with BitBucket, the following error code is sometimes displayed on the frontend:

{"message":"API rate limit exceeded for 35.208.4.157. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

URL where this issue can be seen: https://dahelpguide.luigibella.com/markdown-git/

<img width="1767" alt="Screen Shot 2020-05-08 at 5 24 01 PM" src="https://user-images.githubusercontent.com/29728363/81462789-b8ad5580-9150-11ea-9314-3d2d91bf8e20.png">

**Paste the shortcode and the censored contents of config.json**

`[git-bitbucket-markdown user=luigibella token=5XQ8pvTDW7fJtWHqz86u url="https://bitbucket.org/pacificdisastercenter/disasteraware-master-user-guide/src/master/1.2%20test%20page.md"]`

```
config.json file is not present in this plugin version
```

**To Reproduce**
1. Install Markdown Git Version 0.1 Pushed to Github on March 8th
2. Insert shortcode to Markdown file hosted on Bitbucket

**Screenshots**
<img width="1767" alt="Screen Shot 2020-05-08 at 5 24 01 PM" src="https://user-images.githubusercontent.com/29728363/81462789-b8ad5580-9150-11ea-9314-3d2d91bf8e20.png">

**Comment by nilsnolde** [comment]
Ouch.. yeah right. That indeed is a problem I didn't think about.. Damn it. No matter which provider is chosen the plugin is requesting Github's `/markdown` endpoint. Since that request (currently) is not authenticated, Github rate limits heavily to 60 requests per minute: https://developer.github.com/v3/#rate-limiting

It's alright for 99% of the articles but heavily trafficked blogs will run into problems. Or even during development, as you encountered I guess.

Let me fix that soon. And please bump if I forget about it.

**Comment by nilsnolde** [comment]
Ah, actually I think this is fine the way it is tbh. Github says they restrict to 60 calls per hour **per IP**, meaning a single computer would have to request a post more than once a minute 60 times before the hour ends in order to be rate limited.

I think it's reasonable to assume that that won't happen unless you're in heavy testing.

I'll close but anyone who thinks their users are reading like pros can implement this :)

**Comment by nilsnolde** [comment]
Argh, no idea what's wrong today..

Of course it's a problem.. The "user" is the server and can actually only serve 60 requests per hour which doesn't require a lot of users to achieve.

Ok, this overtakes a lot of things in the priority lane. Will fix asap.

**Comment by nilsnolde** [comment]
Auto-closed by Github and my stupidity. This is fixed now in current `master' @LuigiBella. You'll have to provide your Github credentials in `config.json` to increase the API rate limit.

**Comment by nilsnolde** [comment]
Also this is fixed with 1.0.2 release:
https://wordpress.org/plugins/documents-from-git/

Please re-open if this issue continues happen.
