### ISSUE TITLE
GitLab rate limited

### ISSUE THREAD

**Issue by andrei1058** [gis-ops/wordpress-markdown-git#18]
**Versions**
Wordpress: 5.5.1
Documents for Git: 1.0.2

**Describe the bug**

I'm getting a response message like if I were using a markdown from github, but I'm using a gitlab link. Besides that, I'm getting rate limited too easily even if I provided a username and a token.

```
{"message":"API rate limit exceeded for 54.3*.***.209. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

**Paste the shortcode and the censored contents of config.json**

`[git-gitlab-markdown url="https://gitlab.com/andrei1058/bedwarsproxy/-/blob/development/README.md"]`

```
{
  "limit": 5,
  "classes": "",
  "Github": {
    "user": "",
    "token": ""
  },
  "Bitbucket": {
    "user": "",
    "token": ""
  },
  "Gitlab": {
    "user": "andrei1058",
    "token": "v5v5*V*V+*V*V**%*%"
  }
}
```

**To Reproduce**
1. Create an article with a markdown file
2. Put your credentials in config.json
3. Refresh the web page evert 10 seconds for about 5 minutes
4.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nilsnolde** [comment]
Jup, see here how to avoid :)
https://github.com/gis-ops/wordpress-markdown-git#usage

**Comment by andrei1058** [comment]
1. Why am I getting a github rate limit message if I am using your plugin for gitlab?
2. I've also tried adding user and token the [git tag] but the issue is still there. Also what would the config.json be there for if I'm forced to put my credentials in a tag?

Please read my entire report.

**Comment by nilsnolde** [comment]
I did read your report and my answer still stands:

1. Please read the entire section of the README I pointed you to. It's using Github's /markdown endpoint to generate the markdown, that's why you need it. Irrespective of the provider you're hosting your md file with.
2. That's not doing anything for github auth when you're using gitlab as a host. Putting the credentials into the shortcode will **only** be used for the provider the shortcode targets.

So put the Github user/token into the config.json and you'll find it works.
